### ISSUE TITLE
[L3D] list pools by layer3domain

### ISSUE THREAD

**Issue by miesi** [1and1/dim#121]
During specification I seem to have missed something like
```
ndcli list pools [VLANID|CIDR|POOL] [layer3domain l3d]
```
Something like this:
```
ndcli list pools layer3domain default

ndcli list pools de-kae-bs* layer3domain some-layer-3-domain

ndcli list pools de-kae-bs* layer3domain all
```
There should be auto-complete for layer3domain.

**Comment by zeromind** [comment]
> During specification I seem to have missed something like
> 
> ```
> ndcli list pools [VLANID|CIDR|POOL] [layer3domain l3d]
> ```


Unfortunately it's not easily possible to have that order due to the nature of the `query` (`VLANID|CIDR|POOL`), which supports 3 different types without a keyword. `layer3domain` would be mistaken as `POOL`.

I've implemented it in the other way around (#193), which matches what's available for `ndcli list containers`:
```
Usage: ndcli list pools [layer3domain LAYER3DOMAIN] [VLANID|CIDR|POOL]

 Displays the list of matching pools.

If no query parameter is given, all the pools are selected. Otherwise, the
parameter is tested to determine its type in the following order:

* VLAN_ID: positive integer >=2 and <=4094
* CIDR: address/prefix
* POOL: any string. You may use '*' for matching multiple characters and '?' for
  matching single characters.
```

```
Usage: ndcli list containers [layer3domain LAYER3DOMAIN] [CONTAINER]

 list the children of a container
```
