### ISSUE TITLE
user without rights can delete ip from pool

### ISSUE THREAD

**Issue by miesi** [1and1/dim#88]
Internally tracked as ITOUDP-2966 and GPHDIM-529.

This was implemented by design to ease clean up of DNS.

Now it has become a burden.

Change testcase

change code

run testsuite

**Comment by Srudush** [comment]
The problem lies in `dim/dim/dns.py#rr_delete`

There is no check done if the record can be deleted, but it is instead delegated to `delete_with_references`. That function in return is collecting all records together, that may need to be deleted and then at the end delegates to `free_ipblocks`.
At that point all A or AAAA records are already deleted and only the cleanup of IPs is needed, which is done directly by querying the database with all IPs.
